'use client';
import { useCallback, useEffect, useState } from 'react';
const categories = { content: '문구·콘텐츠', product: '상품·요금', design: '디자인·이미지', bug: '오류·기능', other: '기타' };
export default function ChangeRequestPanel({ adminRequest, active }) {
  const [items, setItems] = useState([]); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { const result = await adminRequest('/api/admin/change-requests'); setItems(result.requests || []); }, [adminRequest]);
  useEffect(() => {
    if (!active) return;
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load().catch((error) => setNotice(error.message));
  }, [active, load]);
  async function create(event) { event.preventDefault(); try { const result = await adminRequest('/api/admin/change-requests', { method: 'POST', body: new FormData(event.currentTarget) }); event.currentTarget.reset(); setItems((current) => [result.request, ...current]); setNotice('수정 신청을 등록했습니다.'); } catch (error) { setNotice(error.message); } }
  async function comment(event, requestId) { event.preventDefault(); const content = new FormData(event.currentTarget).get('content')?.trim(); if (!content) return; try { const result = await adminRequest('/api/admin/change-requests', { method: 'POST', body: JSON.stringify({ action: 'comment', requestId, content }) }); event.currentTarget.reset(); setItems((current) => current.map((item) => item.id === requestId ? { ...item, comments: [...(item.comments || []), result.comment] } : item)); } catch (error) { setNotice(error.message); } }
  return <section className="admin-section admin-panel" data-panel="change-requests"><div className="admin-section-title"><span>08 / CHANGE REQUESTS</span><h2>수정 신청</h2><p>수정 내용과 화면 캡처를 남기고 관리팀과 댓글로 논의합니다.</p></div><form className="change-request-form" onSubmit={create}><label>카테고리<select name="category">{Object.entries(categories).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>제목<input name="title" maxLength="120" required placeholder="수정할 항목을 요약해 주세요" /></label><label className="wide">수정 내용<textarea name="description" rows="6" maxLength="5000" required placeholder="수정 위치와 원하는 변경 내용을 구체적으로 적어 주세요." /></label><label className="wide">캡처 화면<input name="screenshots" type="file" accept="image/jpeg,image/png,image/webp" multiple /><small>JPG · PNG · WebP, 파일당 5MB</small></label><button className="admin-save">수정 신청 등록</button></form>{notice && <p className="admin-notice">{notice}</p>}<div className="change-request-list">{items.map((item) => <article className="change-request-item" key={item.id}><header><span>{categories[item.category]}</span><small>{new Date(item.created_at).toLocaleString('ko-KR')}</small></header><h3>{item.title}</h3><p>{item.description}</p>{item.screenshot_urls?.length > 0 && <div className="change-request-shots">{item.screenshot_urls.map((url) => <a href={url} key={url} target="_blank" rel="noreferrer"><img src={url} alt={`${item.title} 첨부 캡처`} /></a>)}</div>}<footer>{item.created_by_email}</footer><div className="change-request-comments">{(item.comments || []).map((reply) => <p key={reply.id}><b>{reply.author_email}</b>{reply.content}<small>{new Date(reply.created_at).toLocaleString('ko-KR')}</small></p>)}</div><form className="change-request-comment" onSubmit={(event) => comment(event, item.id)}><input name="content" maxLength="2000" required placeholder="관리자 댓글" /><button>댓글 등록</button></form></article>)}</div></section>;
}
